version: '3.8'

services:
  # --- MODULE D: DATABASE STORAGE ---
  mongo:
    image: mongo:6.0
    container_name: dota_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: dota_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      # Credencials per connectar-se a la Base de Dades (intern)
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongo:27017/
      
      # AFEGEIX AIXÃ’: Credencials per entrar a la WEB (Login)
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
    depends_on:
      - mongo

volumes:
  mongo_data: